---
output:
  word_document: default
  html_document: default
---
```{r libraries}
library(tidyverse)
library(skimr)
library(tidymodels)
library(GGally)
library(gridExtra)
```

```{r}
ames <- read_csv("ames_student.csv")
```

```{r}
str(ames)
summary(ames)
```

```{r}
ames = ames %>% mutate_if(is.character,as_factor)
```

```{r}
str(ames)
```

```{r}
skim(ames)
```

```{r}
ames2 = ames %>% dplyr::select("MS_SubClass", "Lot_Area", "Neighborhood", "Bldg_Type", "House_Style", "Overall_Qual", "Gr_Liv_Area", "Garage_Cars", "Garage_Area", "Total_Bsmt_SF", "First_Flr_SF", "Full_Bath", "Year_Built", "Year_Remod_Add", "TotRms_AbvGrd", "Mo_Sold", "Year_Sold", "Above_Median")
```

```{r}
summary(ames2)
glimpse(ames2)
```

```{r}
ggplot(ames2, aes(x=MS_SubClass,fill=Above_Median)) + geom_bar() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) #changing alpha is helpful when many points may overlap
ggplot(ames2, aes(x=Above_Median,y=Lot_Area)) + geom_boxplot()
ggplot(ames2, aes(x=Neighborhood,fill=Above_Median)) + geom_bar() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
ggplot(ames2, aes(x=Bldg_Type,fill=Above_Median)) + geom_bar()
```

```{r}
ggplot(ames2, aes(x=House_Style,fill=Above_Median)) + geom_bar() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

ggplot(ames2, aes(x=Overall_Qual,fill=Above_Median)) + geom_bar() + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

ggplot(ames2, aes(x=Above_Median,y=Gr_Liv_Area)) + geom_boxplot()

ggplot(ames2, aes(x=Garage_Cars, fill=Above_Median)) + geom_bar()
```

```{r}
ggplot(ames2, aes(x=Above_Median,y=Garage_Area)) + geom_boxplot()

ggplot(ames2, aes(x=Above_Median,y=Total_Bsmt_SF)) + geom_boxplot()

ggplot(ames2, aes(x=Above_Median,y=First_Flr_SF)) + geom_boxplot()

ggplot(ames2, aes(x=Full_Bath, fill=Above_Median)) + geom_bar()
```

```{r}
ggplot(ames2, aes(x=Year_Built, fill=Above_Median)) + geom_bar()

ggplot(ames2, aes(x=Year_Remod_Add, fill=Above_Median)) + geom_bar()

ggplot(ames2, aes(x=TotRms_AbvGrd, fill=Above_Median)) + geom_bar()

ggplot(ames2, aes(x=Mo_Sold, fill=Above_Median)) + geom_bar()

ggplot(ames2, aes(x=Year_Sold, fill=Above_Median)) + geom_bar()
```

```{r}
t1 = table(ames2$Year_Sold, ames2$Above_Median) #create a table object

t1

prop.table(t1, margin = 2 ) #crosstab with proportions
```

